spring:
  datasource:
    url: jdbc:h2:mem:rutaseg;mode=mysql;DATABASE_TO_LOWER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  profiles:
    active: ${SCOPE:local}

aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    files-bucket: ${AWS_S3_FILES_BUCKET}

logging:
  pattern:
    file: '%d %p %c{1.} [%t] %m%n'
    console: '%d{yyyy-MM-dd HH:mm:ss} [%t] %-5p %logger{0} [request_id:%X{requestId}] - %m%n'

jwt:
  secretKey: ${JWT_SECRET_KEY}

session:
  knownOrigins: ${KNOWN_ORIGINS:}
  allowAllOrigins: ${ALLOW_ALL_ORIGINS:true}

email:
  username: ${EMAIL_USERNAME}
  password: ${EMAIL_PASSWORD}
  internal:
    to: ${INTERNAL_EMAIL_TO:email@host.com}

server:
  port: 5000
