spring:
  datasource:
    url: jdbc:mysql://gexlog-beta-db.ci6uiv75rk1m.us-east-2.rds.amazonaws.com:3306/gexlog
    username: root
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
files:
  directory: ${FILES_DIRECTORY}